apache/incubator-hugegraph-doc

quickstart/hugegraph-client.md

change the postfix name of hugegraph-server from '.html' to '.md'

fix the missing hugegraph-server link

---

clients/restful-api/propertykey.md

the element defined in the source code is 'data_type',so the request body should filled with 'data_type' not  'dataType'

modify the request_body

---

clients/gremlin-console.md
guides/config-option.md
quickstart/hugegraph-client.md
quickstart/hugegraph-studio.md

#5 
Change-Id: I735663c4b4960a107f4af6991111d6b583314cd4

Move auth-related config options to Server & API region

---

quickstart/hugegraph-loader.md

Change-Id: If2d0de68930de63250b6de4c1746233725f75661

fix example bug of struct.json config file

---

config/config-option.md

Change-Id: Iaf7f30f38f97e34b1c92d4aecbc9317b37b5586d

add config options of v0.9

---

quickstart/hugegraph-loader.md

Change-Id: Ia3b4128b3353e0cd9d3a6e7c78885b53aa18453a

update hugegraph-loader doc for release-0.9.2

---

clients/hugegraph-client.md
clients/restful-api/edge.md
clients/restful-api/rebuild.md
clients/restful-api/traverser.md
quickstart/hugegraph-tools.md

1. source_in_ring args for Rings API
2. shard index and unique index in client doc
Change-Id: Ib4b2bceee09465b520f8ba04fdb20f046a0bc6ee

update doc for v0.10

---

quickstart/hugegraph-tools.md

Change-Id: I305b3908b4cab51bb6237410e8c42a7ceaf4c440

update tools task-clear --force args

---

config/config-option.md

Change-Id: I4620836d0aca850842fa4db76b76566f38b0138f

Optimize config option description

---

quickstart/hugegraph-tools.md

Change-Id: I1eea90fc6f7c6aedd32295fb3797cdf14fb7b9a3

add doc for tools migrate subcommand

---

clients/restful-api/edge.md
clients/restful-api/vertex.md

Change-Id: I89baa7c0464b5a8573f63a1db910a18cd9f1ede9

Add api for vertex/edge batch update properties

---

quickstart/hugegraph-tools.md

Change-Id: I1c28bc278d2cc627514f2d76bf0537630c9eb9dc

update tools doc for version 1.5.0

---

quickstart/hugegraph-tools.md

Change-Id: Iaf587791be849c6b75f2ce10f385cc0c479938b1

delete type args for dump description

---

clients/restful-api/edgelabel.md
clients/restful-api/vertexlabel.md

Change-Id: Ib77eab40b0a324a04a06e0ecb223e6d185a8f497

add ttl description for vertexlabel and edgelabel

---

quickstart/hugegraph-tools.md

Change-Id: Ibc8af9432a8f154503a2b372e3726cf2dfdbd76e

remove --protocol args

---

quickstart/hugegraph-tools.md

Change-Id: I00246b8488cba4801c9cd279cc824cee1f3ee4a2

improve tools command args

---

README.md
changelog/hugegraph-0.11.2-release-notes.md

Change-Id: Ie0de3b17ca805daf042a68776fa01c4204e98ded

change web visual platform from studio to hubble

---

clients/restful-api/traverser.md

Change-Id: I222a6f3c073a0e5744373bcc60b422997fe771fc

Vertices only supports single vertex label, not vertex label list

---

clients/restful-api/auth.md
config/config-https.md

Change-Id: I4e62d4e248329758358a9eb6d197d0d9ef49657e

fix security risk

---

clients/restful-api/auth.md
quickstart/hugegraph-tools.md

Change-Id: Ibe9a17a3b31212e2ba6bf28eef042b342e1b3dd1

fix security error

---

clients/restful-api/auth.md

Change-Id: Idd7b00c016171666194a241689797e7fc2d87c5f

fix security error in doc with example password

---

SUMMARY.md
clients/hugegraph-api.md
clients/hugegraph-client.md
clients/restful-api/edge.md
clients/restful-api/gremlin.md
clients/restful-api/traverser.md
clients/restful-api/vertex.md
config/config-authentication.md
guides/desgin-concept.md
guides/faq.md
language/hugegraph-example.md

Fixed #51 #52 and some desc:
1. remove some outdated design conception
2. adjust `REST-API` &  Guide` position
3. add some default params for client
4. add some comments for `skip_degree`
5. add comment for Cassandra page
6. add auth-api request example & link page in rest-menu

doc: update some api format & description

---

clients/restful-api/edge.md
clients/restful-api/edgelabel.md
clients/restful-api/graphs.md
clients/restful-api/gremlin.md
clients/restful-api/propertykey.md
clients/restful-api/vertex.md
clients/restful-api/vertexlabel.md

TODO: this pr need address comments later

Improve some RESTful api details

---

clients/restful-api/propertykey.md

Change-Id: Id0ace9c2c1d1ce040e805368281b406a3162f2ca

update property key api for olap pk

---

clients/hugegraph-api.md
clients/restful-api/auth.md
clients/restful-api/edgelabel.md
clients/restful-api/graphs.md
clients/restful-api/gremlin.md
clients/restful-api/indexlabel.md
clients/restful-api/other.md
clients/restful-api/propertykey.md
clients/restful-api/rebuild.md
clients/restful-api/schema.md
clients/restful-api/task.md
clients/restful-api/variable.md
clients/restful-api/vertexlabel.md

also adjust old docs
Change-Id: I595684d5ca20e8f34693b520836366df7c5535e5

add schema api description

---

SUMMARY.md

Change-Id: Ic901c149cc5d29aa33f51040a467a201af0b4cef

add schema api entrance in navigate bar

---

clients/restful-api/gremlin.md

Change-Id: Ibb5d6f410f45b96c9a65033e7ac33e49426797e3

fix gremlin job return code

---

changelog/hugegraph-0.12.0-release-notes.md

Change-Id: I9a9750df1389869bca5347796be543a92885ea57

add hugegraph-0.12.0-release-notes.md

---

SUMMARY.md
download.md

Change-Id: Ie78d14317c63aef1dc9082dba88e2868af3a2192

fix release date of 0.12.0

---

themes/docsy/layouts/partials/navbar.html

hidden Blog and About menu  Fix #102

hidden Blog and About menu  Fix #102

---

content/en/docs/quickstart/hugegraph-loader.md

Translate hugegraph-loader.md into english

translate: hugegraph-loader.md into english

---

content/cn/_index.html
content/en/_index.html

`Incubating ` tag is required before graduation

chore: add incubating tag

---

content/en/docs/quickstart/hugegraph-server.md

translate: hugegraph-server.md into english

translate: hugegraph-server.md into english

---

content/en/docs/clients/hugegraph-client.md

translate client api to English

---

themes/docsy/assets/scss/main.scss
themes/docsy/layouts/partials/footer.html

add incubator label #18
before:
---
after:

site: add incubator label

---

content/cn/docs/quickstart/hugegraph-loader.md
content/en/docs/quickstart/hugegraph-loader.md

related to: https://github.com/apache/incubator-hugegraph-toolchain/pull/263

doc: add custom_sql option for jdbc source

---

content/en/docs/clients/restful-api/rebuild.md
content/en/docs/clients/restful-api/task.md

fix conflict and Translate RESTfullAPI -> Rebuild API and RESTfullAPI -> Task API

issues-109  restapi -> rebuild and task API

---

themes/docsy/layouts/partials/footer.html

add background-color
before:
after:

site: fix bg color

---

content/cn/docs/config/config-option.md
content/en/docs/config/config-option.md

add HBase pre-splite cofig options

add HBase pre-splite config options

---

config.toml

change incubator-hugegraph to incubator-hugegraph-doc

fix github_repo config

---

config.toml

mailto dev@hugegraph.apache.org

---

.asf.yaml

This commit also test the required CI for

chore: enable the rules in .asf.yml

---

content/cn/docs/quickstart/hugegraph-server.md
content/en/docs/quickstart/hugegraph-server.md

**add HBase pre-splite config options in quickstart**
**before update**
**after update**

add HBase pre-splite config options in quickstart

---

content/cn/_index.html
content/en/_index.html

chore: update the project name

---

content/en/docs/quickstart/hugegraph-tools.md

translate hugegraph tools doc

---

content/cn/docs/contribution-guidelines/validate-release.md
content/en/docs/contribution-guidelines/validate-release.md

add binary package startup script

enhance validate doc

---

content/cn/docs/changelog/hugegraph-1.0.0-release-notes.md
content/en/docs/changelog/hugegraph-1.0.0-release-notes.md

remove `xx` in release notes now, update them later

fix release format

---

content/en/docs/clients/restful-api/edge.md

update edge.md for fuzzy query

---

.asf.yaml

follow https://github.com/apache/incubator-hugegraph/pull/2128#issuecomment-1469844210

chore: update .asf.yaml for mail rules

---

content/cn/docs/quickstart/hugegraph-server.md
content/en/docs/quickstart/hugegraph-server.md

- This PR closes https://github.com/apache/incubator-hugegraph-doc/issues/209

fix wrong path in hugegraph-server.md

---

content/cn/docs/quickstart/hugegraph-loader.md
content/en/docs/quickstart/hugegraph-loader.md

修复loader文档中代码示例未更新的问题
fixed #216

Branch fix load example

---

content/cn/docs/clients/restful-api/schema.md
content/en/docs/clients/restful-api/schema.md

docs: modify and translate schema-api

---

content/cn/docs/quickstart/hugegraph-client.md

docs: fix client jump link

---

README.md

issue #257
Add mail subscribe way in README

docs: add email list subscribe guide

---

content/cn/docs/contribution-guidelines/subscribe.md
content/en/docs/contribution-guidelines/subscribe.md

Subtask of #257, we could use a `TODO` tag to check the status: (**click** the button directly to mark it as done)
**After：**

doc: provide translate of subscribe.md

---

content/cn/docs/config/config-guide.md
content/cn/docs/quickstart/hugegraph-server.md
content/en/docs/config/config-guide.md
content/en/docs/quickstart/hugegraph-server.md

fix: https://github.com/apache/incubator-hugegraph/issues/2230 and https://github.com/apache/incubator-hugegraph/issues/2175
closes: #203

fix: update mysql backend and multi graphs

---

content/en/docs/config/config-guide.md
content/en/docs/quickstart/hugegraph-server.md

chore: use option instead

---

content/cn/docs/clients/restful-api/traverser.md
content/en/docs/clients/restful-api/traverser.md

* kout & kneighbor: filtering for edge & vertex
* kout: traverse mode bfs & dfs
* kout & kneighbor: with_edge params
- [[Feature Summary] Enhancement and optimization OLTP algorithm & api #2276](https://github.com/apache/incubator-hugegraph/issues/2276)

doc: update content about kout & kneighbor new feature

---

content/cn/docs/quickstart/hugegraph-loader.md
content/en/docs/quickstart/hugegraph-loader.md

update hugegraph-loader.md,add kafka as input source

doc: update hugegraph-loader.md

---

content/en/docs/changelog/hugegraph-1.2.0-release-notes.md

create hugegraph-1.2.0-release-notes.md

chore: create hugegraph-1.2.0-release-notes.md

---

content/en/docs/changelog/hugegraph-1.2.0-release-notes.md

doc(release-note): computer release note 1.2.0

---

content/en/docs/changelog/hugegraph-1.2.0-release-notes.md

doc: update toolchain release-note 1.2.0

---

content/en/docs/changelog/hugegraph-1.2.0-release-notes.md

doc(release-note): commons and server release note 1.2.0

---

content/cn/docs/contribution-guidelines/hugegraph-server-idea-setup.md

As title, inspired by @imbajin.
> EN doc will be synchronized later.

doc(setup-idea): consider the scenario of configuring authenticator in Java 11 for server

---

content/cn/docs/contribution-guidelines/hugegraph-server-idea-setup.md
content/en/docs/contribution-guidelines/hugegraph-server-idea-setup.md

1. fix https://github.com/apache/incubator-hugegraph-doc/pull/326#discussion_r1464231528
2. synchronize EN doc in #326

doc(setup-idea): sync EN doc for previous PR

---

content/cn/docs/quickstart/hugegraph-server.md

doc: fix doc link 404

---

content/cn/docs/download/download.md
content/en/docs/download/download.md

chore: update 1.3.0 cn download page

---

content/cn/docs/clients/gremlin-console.md
content/en/docs/clients/gremlin-console.md

refer https://github.com/apache/incubator-hugegraph/pull/2518

chore: improve docs for gremlin console

---

README.md

- close #xxx  
-  updated the 'How to Contribute' link to point to the official website instead of an empty `contributing.md` file.
- delete redundant "Guildlines"

doc: update "How to Contribute" link and delete redundant "Guildlines"

---

content/en/docs/quickstart/hugegraph-hubble.md

Translation correction: Multi-image -> Multi-graphs
- Fix docs typo.

fix: translation correction.

---

content/cn/docs/clients/restful-api/graphs.md
content/en/docs/clients/restful-api/graphs.md

- fix https://github.com/apache/incubator-hugegraph/issues/2530

fix: misleading in dynamic crate graph api

---

content/cn/docs/changelog/hugegraph-1.3.0-release-notes.md
content/cn/docs/changelog/hugegraph-1.5.0-release-notes.md
content/en/docs/changelog/hugegraph-1.3.0-release-notes.md
content/en/docs/changelog/hugegraph-1.5.0-release-notes.md

doc: update 1.5.0 release notes

---

config.toml
themes/docsy/assets/vendor/bootstrap/site/layouts/partials/analytics.html

chore: remove Google Analytics from website

---

themes/docsy/layouts/_default/baseof.html

fix: critical CSP problem

---

themes/docsy/layouts/_default/baseof.html

fix: enhance CSP rule

---

themes/docsy/layouts/partials/head.html

fix: csp inline
