apache/incubator-hugegraph-doc

quickstart/hugegraph-server.md
change the postfix name of three links from '.html' to '.md'
=> fix three missing links

clients/restful-api/graph.md, clients/restful-api/indexlabel.md, clients/restful-api/traverser.md
Change-Id: I9114c0c29e89c8b24d771270a44c8e79aca1403f
=> Paths, crosspoints, rings, rays, mode, index create API description

clients/restful-api/traverser.md
Change-Id: I211a39c16fe519e3237c7451e6e89d6c69ccaa3b
=> fix bug rings and rays max_depth

config/config-guide.md
implemented: #18
Change-Id: Ic6a5eb2caa057cf63f9bc282f9c0be725b21afb9
=> Add description of changing gremlin server host and port

README.md, guides/architectural.md, language/hugegraph-example.md, language/hugegraph-gremlin.md, quickstart/hugegraph-client.md
Change-Id: I40677804ca9803886a915d806531457756a4ba7b
=> Modify homepage content

SUMMARY.md, changelog/hugegraph-0.9.2-release-notes.md, download.md
Change-Id: Ifbc734144643cea69ed3bc7b9b12fe5361e3fc77
=> add hugegraph-0.9.2 release notes

quickstart/hugegraph-tools.md
Change-Id: I74bb2d396fc8d67fbc4b7c404615cdfdea0db079
=> update hugegraph-tools doc for release-0.9.2

clients/restful-api/traverser.md
fix https://github.com/hugegraph/hugegraph/issues/504
=> Unify limit and capacity description of k-neighbor traverser API

config/config-option.md
show how to config hbase zookeeper ip addresses explicitly
=> update hbase zookeeper ip addresses config

SUMMARY.md
Change-Id: If1de9a8fa427b7ac3b1b2b0a6dba5b227f474e51
=> Add rank api link on navi

README.md, quickstart/hugegraph-server.md
Change-Id: I9ce9fcef6ee8b28e2bd5ccfc417c026a6393dbf2
=> Add some feature descriptions to readme file

clients/restful-api/graphs.md, clients/restful-api/rebuild.md, guides/backup-restore.md
Change-Id: Ia25a28e93fb1f9ac20dbba9f9370a5b7060ce579
=> Improve backup/restore doc

changelog/hugegraph-0.11.2-release-notes.md
Change-Id: Ie0a9037789fda4c444eaf697fb66663195a2c21a
=> add 0.11.2 release notes

content/en/docs/changelog/_index.md, content/en/docs/contribution-guidelines/_index.md, content/en/docs/contribution-guidelines/contribute.md, content/en/docs/contribution-guidelines/subscribe.md
fixed #111 
refer to [Spark](https://spark.apache.org/contributing.html)
=> fix: contribution guide page 404

content/en/docs/quickstart/hugegraph-client.md
Translate the quick start of client.
=> translate: hugegraph-client.md into english

themes/docsy/assets/scss/main.scss, themes/docsy/layouts/partials/footer.html
Optimize the footer style of the  website
before:
---
after:
=> site: update footer

content/cn/docs/clients/restful-api/propertykey.md, content/en/docs/clients/restful-api/propertykey.md
An error will be reported according to the original document, like:
`Unrecognized field "property_key" (class com.baidu.hugegraph.api.schema.PropertyKeyAPI$JsonPropertyKey), not marked as ignorable (9 known properties: "check_exist", "properties", "aggregate_type", "id", "cardinality", "data_type", "name", "user_data", "write_type"])
at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 2, column: 23] (through reference chain: com.baidu.hugegraph.api.schema.PropertyKeyAPI$JsonPropertyKey["property_key"])`
[master branch pr](https://github.com/apache/incubator-hugegraph-doc/pull/134)
=> fix: bad request body simple in propertykey.md

content/en/docs/config/config-option.md
impelement https://github.com/apache/incubator-hugegraph-doc/issues/109
translate config doc
=> translate config config-option.md to English

content/en/docs/clients/gremlin-console.md
impelement https://github.com/apache/incubator-hugegraph-doc/issues/109
translate gremlin-console.md doc
=> translate gremlin console to English

content/cn/docs/clients/restful-api/graphs.md, content/en/docs/clients/restful-api/graphs.md
Append new api:
drop graph、create snapshot、resume snapshot、compact、get|modify graph_read_mode.
And translate graphs.md
=> update:append new api for graphs & translate

.github/workflows/hugo.yml
I read the gohugo.io's doc, and compare the Apache ShenYu deploy.yml. The confusing discussion[1] was clear. But this action could not set up to my repository, because the settings > pages could not work exactly. 
Pls review, and test.
[1] : [#147 ](https://github.com/apache/incubator-hugegraph-doc/issues/147)
=> chore: enable hugo action to build site automaticly

contribution.md
=> fix download hugo url err

content/en/docs/clients/restful-api/vertex.md
=> update vertex.md for fuzzy query

.github/workflows/validate-release.yml, dist/validate-release.sh
validate release actions support mulit os, test see:
https://github.com/z7658329/incubator-hugegraph-doc/actions/runs/4165118148/jobs/7207673497
=> validate release actions support mulit os

content/cn/docs/quickstart/hugegraph-client.md, content/en/docs/quickstart/hugegraph-client.md
fix #217 
将示例代码中的baidu包替换成apache
=> Branch fix client

content/cn/docs/quickstart/hugegraph-loader.md, content/en/docs/quickstart/hugegraph-loader.md
update loader example from here: https://github.com/apache/incubator-hugegraph-toolchain/tree/master/hugegraph-loader/assembly/static/example/file
=> docs: sync loader example 

content/cn/docs/contribution-guidelines/hugegraph-server-idea-setup.md, content/cn/docs/quickstart/hugegraph-server.md, content/en/docs/contribution-guidelines/hugegraph-server-idea-setup.md, content/en/docs/quickstart/hugegraph-server.md
The [Quick Start](https://hugegraph.apache.org/docs/quickstart/hugegraph-server/) section provides instructions on how to start and stop HugeGraphServer using scripts. However, for developers, this method may not be convenient as it is not integrated with IDE tools and can be difficult to debug. 
So I add a guide to explain how to run and debug HugeGraphServer on the Linux platform using IntelliJ IDEA.
I have read the CLA Document and I hereby sign the CLA
=> doc: add hugegraph server setup guide for IDEA

config.toml
Subtask of #257, we could use a `TODO` tag to check the status: (**click** the button directly to mark it as done)
After:
=> doc: update the community page

content/cn/docs/clients/gremlin-console.md, content/cn/docs/contribution-guidelines/hugegraph-server-idea-setup.md, content/cn/docs/quickstart/hugegraph-server.md, content/en/docs/clients/gremlin-console.md, content/en/docs/contribution-guidelines/hugegraph-server-idea-setup.md, content/en/docs/quickstart/hugegraph-server.md
When starting HugeGraphServer with the script or with IDEA, the log4j configuration file being read is not the same file, which may cause some confusion for new developers. Therefore, I have added this part of the content to clarify it.
The gremlin-console guide is for PR https://github.com/apache/incubator-hugegraph/pull/2231
> EN doc will be synchronized later.
=> doc: update Log4j2 configuration and gremlin-console guide

content/cn/docs/config/config-guide.md, content/cn/docs/contribution-guidelines/hugegraph-server-idea-setup.md, content/en/docs/config/config-guide.md, content/en/docs/contribution-guidelines/hugegraph-server-idea-setup.md
1. unify `sslmode` -> `ssl_mode`
2. update conf file path according to https://github.com/apache/incubator-hugegraph/blob/master/hugegraph-dist/src/main/java/org/apache/hugegraph/cmd/InitStore.java#L60-L67
=> chore: fix ssl mode & conf path

content/cn/docs/quickstart/hugegraph-computer.md, content/en/docs/quickstart/hugegraph-computer.md
> fix of the issue https://github.com/apache/incubator-hugegraph-doc/issues/277
Fix the page: 
https://hugegraph.apache.org/cn/docs/quickstart/hugegraph-computer/  https://hugegraph.apache.org/docs/quickstart/hugegraph-computer/
update the outdated download link of computer
The Updated page looks like:
=> doc: update the outdated computer download link

content/cn/docs/clients/restful-api/edge.md, content/en/docs/clients/restful-api/edge.md
> SubTask of [[Improvement] RESTful API request/response content need update #260](https://github.com/apache/incubator-hugegraph-doc/issues/260)
Fix this page: https://hugegraph.apache.org/cn/docs/clients/restful-api/edge/
I use **Postman** to test the Edge APIs, and [this](https://gist.githubusercontent.com/VGalaxies/5a5fed9cac5c45a1ba9a902f4850cfb2/raw/f74c84d3435b23917d87234775ae04ec483a966a/hugegraph-edge.postman_collection.json) is the corresponding test configuration collection. By importing and executing it in the order specified in the documentation, theoretically consistent results can be observed.
The server is deployed locally and can be accessed at `127.0.0.1:8080`.
By the way, I'm not quite clear about the usage of the `keepStartP` request parameter in the [list …
=> doc: update outdated doc for edge api

content/cn/docs/quickstart/hugegraph-hubble.md, content/cn/docs/quickstart/hugegraph-server.md, content/en/docs/quickstart/hugegraph-hubble.md, content/en/docs/quickstart/hugegraph-server.md
1. add the server preload.
2. add how to deploy hubble.
1. https://github.com/apache/incubator-hugegraph/issues/840
=> doc: add server preload and hubble deploy

content/cn/docs/clients/restful-api/graphs.md, content/en/docs/clients/restful-api/graphs.md
fix #285 
line126:
gremlin.graph=org.apache.hugegraph.auth.HugeFactoryAuthProxy
=> doc: update gremlin config in graphs.md

content/cn/docs/quickstart/hugegraph-computer.md, content/en/docs/quickstart/hugegraph-computer.md
- After this PR is merged https://github.com/apache/incubator-hugegraph-computer/pull/259, computer-side namespace has been modified from `hugegraph-computer-system` to `hugegraph-computer-operator-system`
- Make corresponding changes in hugegraph-doc.
=> doc: update computer namespace in example

content/cn/docs/clients/restful-api/_index.md, content/cn/docs/clients/restful-api/metrics.md, content/en/docs/clients/restful-api/_index.md, content/en/docs/clients/restful-api/metrics.md
we dont have metric api doc,so user even dont know it.
=> feat(website): add metric api doc

.github/workflows/validate-release.yml, dist/validate-release.sh
This PR is a subtask of https://github.com/apache/incubator-hugegraph-doc/pull/307, and it includes the following changes:
1. Add [ASF category B license](https://www.apache.org/legal/resolved.html#category-b) validation
2. Modify some incorrect entries for existing category X license validation based on (https://www.apache.org/legal/resolved.html#category-b)
=> Fix: add ASF category B validation and modify category X entries for validating HugeGraph 1.2.0 release

.github/workflows/validate-release.yml, dist/validate-release.sh
As title, if double quotes are not added, an error will occur during grep:
```text
grep: License|BSD-4-Clause|\bBCL\b|JSR-275|Amazon: No such file or directory
grep: Software: No such file or directory
grep: License|\bRSAL\b|\bQPL\b|\bSSPL|\bCPOL|\bNPL1|Creative: No such file or directory
grep: Commons: No such file or directory
grep: Non-Commercial: No such file or directory
```
=> fix: double quotes to avoid spaces in grep for validating release

content/en/docs/quickstart/hugegraph-computer.md
1. claim jdk11
2. re-order title
=> doc(quickstart): computer claim jdk11

dist/validate-release.sh
related to https://github.com/apache/incubator-hugegraph-doc/pull/197
=> chore(dist): improve validate-release.sh

content/cn/docs/contribution-guidelines/hugegraph-server-idea-setup.md, content/en/docs/contribution-guidelines/hugegraph-server-idea-setup.md
Improve documentation surrounding the quickstart guide. Encountered an issue where the RaftRequests file was not correctly compiled. Updated guide to provide solution through rebuilding folder via Maven rebuild
Updated potential issues list to include the issue of compilation not correctly generating the RPC files and included solution of rebuilding folder via Maven. Screenshot of website local build + new content located below.
=> fix: enhance the code reading experience for lacking RPC generated files

dist/validate-release.sh
=> fix: validate-release.sh for 1.3.0

content/cn/docs/quickstart/hugegraph-hubble.md, content/en/docs/quickstart/hugegraph-hubble.md
-  Currently, the git download target directory and the cd target file directory are inconsistent, so we are trying to unify them
- Change "cd incubator-hugegraph-toolchain" in  en doc  Section 2.3 to "cd hugegraph-toolchain"
- Change "cd incubator-hugegraph-toolchain" in  cn doc Section 2.3 to "cd hugegraph-toolchain"
- In the source compilation section, remove the node and yarn installation flow (en doc & cn doc)
- The plugin `frontend-maven-plugin` has been added to `hugegraph-hubble/hubble-be/pom.xml`. To compile hubble, we do not need to install `Nodejs V16.x` and `yarn` environment in your local environment in advance.
=> doc(hubble): enhance hubble usage doc/command

themes/docsy/layouts/partials/footer.html
Make the project-specific security page more prominent by linking to it from the website footer.
(also changed some links to https)
=> Link to HugeGraph-specific security page from footer

content/cn/docs/config/config-guide.md, content/en/docs/config/config-guide.md
refine rest-server.property documentation
related to https://github.com/apache/incubator-hugegraph/pull/2610
=> refine rest-server.property documentation

content/en/docs/guides/faq.md
I am interested in updating the documentation and integrating instructions on how ScyllaDB can be utilized as a backend for HugeGraph. This is the first step of many changes in this direction. As someone who has been working with graphs for more than 6 years now, HugeGraph caught my attention as a potential solution to challenges I have encountered over the last few years.
=> doc: update Scylladb integration faq

content/cn/docs/config/config-guide.md, content/cn/docs/config/config-option.md, content/en/docs/config/config-guide.md, content/en/docs/config/config-option.md
Add jvm(in-heap) memory monitor related config options to doc.
=> doc: add JVM(in-heap) memory monitor config desc

.github/workflows/validate-release.yml, dist/validate-release.sh
=> chore(dist): update validate release scripts for releasing 1.5.0

content/cn/docs/changelog/hugegraph-1.3.0-release-notes.md, content/cn/docs/changelog/hugegraph-1.5.0-release-notes.md, content/cn/docs/config/config-authentication.md, content/cn/docs/quickstart/hugegraph-client.md, content/cn/docs/quickstart/hugegraph-hubble.md, content/cn/docs/quickstart/hugegraph-loader.md, content/cn/docs/quickstart/hugegraph-server.md, content/en/docs/config/config-authentication.md, content/en/docs/introduction/README.md, content/en/docs/quickstart/hugegraph-ai.md, content/en/docs/quickstart/hugegraph-client.md, content/en/docs/quickstart/hugegraph-computer.md, content/en/docs/quickstart/hugegraph-hubble.md, content/en/docs/quickstart/hugegraph-loader.md, content/en/docs/quickstart/hugegraph-server.md
- update docker version to 1.5.0
=> chore: update version to 1.5.0

themes/docsy/layouts/_default/baseof.html, themes/docsy/layouts/partials/head.html
=> fix: move csp rule

README.md, content/en/docs/introduction/README.md
Minor docs updates as well as PD and Store descriptions.
=> Minor homepage docs updates and add PD and Store descriptions

content/cn/docs/quickstart/hugegraph-server.md
Chapter 5.2.2 has an indentation issue in the docker-compose.yml code.
- fix hugegraph-server.md chapter 5.2.2 indentation problem
- origin 
- after fix
=> fix hugegraph-server.md chapter 5.2.2
